name: Test Scripts

on: 
    workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Extract 3 characters from input string
        run: |
          input_string="project-cw-qaa-123455"
          extracted_chars=$(echo $input_string | awk -F'-' {$3})
          echo "Extracted Characters: $extracted_chars"